### ISSUE TITLE
Pen event mapping by external process / library (custom filters)

### ISSUE THREAD

**Issue by LoganDark** [funkey/remarkable_intercept#12]
My RM2 suffers from an issue where in specific spots of the display, the drawing tools are slightly offset from the physical tip. So much so that the line appears next to the tip.

![image](https://user-images.githubusercontent.com/4723091/148241459-26202756-e402-4a1c-bec5-7866e456b9b9.png)
![image](https://user-images.githubusercontent.com/4723091/148243167-2dc6df74-eab4-45fa-bbea-acaebeec83ad.png)

Due to this I want to make another program that uses recept to fix the misalignment in the miscalibrated portions of the display. However, recept doesn't support custom filters yet :( so I'm opening this issue to track that.

Some ideas:
- recept uses a pipe or a unix socket or something directly (only supports 1 custom filter, stalls if the filter ever crashes or is missing)
- recept runs a unix socket server and accepts connections from other processes wanting to offer filters (sounds complex)
- recept accepts (well, reads from xochitl) a command-line argument pointing to a dynamic library (sounds like the most reasonable solution)

**Comment by LoganDark** [comment]
I recently discovered that LD_PRELOAD supports multiple libraries in a row, so this actually isn't the issue I thought it was

**Comment by funkey** [comment]
I think the easiest solution would probably be to directly apply the offset in `recept` and compile a custom version that fixes your issue. This way, you don't have to chain several `LD_PRELOAD`s together.

**Comment by LoganDark** [comment]
I don't actually use ReCept - I just saw that it already did something that I wanted to do (intercept pen events and modify them), and thought about using it to achieve what I wanted.

FYI, this is not a simple offset. Different regions of the display have different error and therefore a much more complex calibration sequence is needed. Extending ReCept's codebase to support this directly would be a bit niche, especially since a companion app is required to collect the calibration data anyway.
